Traceback (most recent call last):
  File "<ipython-input-13-d998cc8ab29a>", line 3, in <module>
    raise Exception("This is the error message!")
Exception: This is the error message!
